---
# tasks file for selinux (CentOS specific)

- name: Check if foo.rpm is installed
  command: rpm -q selinux-policy
  register: rpm_check
  failed_when: false
  changed_when: no

- name: Install libselinux-python bindings
  yum: name=libselinux-python state=present
  tags: selinux
  when: rpm_check.stdout.find('is not installed') != -1

- name: Set SELinux policy and state
  selinux: policy={{ selinux_policy }} state={{ selinux_state }}
  tags: selinux
  when: rpm_check.stdout.find('is not installed') != -1
