---
# tasks file for selinux

- name: Install libselinux-python bindings
  yum: name=libselinux-python state=present

- name: Set SELinux state to permissive
  selinux: policy=targeted state=permissive
